export { default as Homepage } from './HomePage';
export { default as PageNotFound } from './PageNotFound';
export { default as Picture } from './Picture';
export { default as Header } from './Header';
export { default as Photos } from './Photos';
export { default as Spinner } from './Spinner';
export { default as Pages } from './Pages';
export { default as SearchPage } from './SearchPage';
export { default as SearchHistory } from './SearchHistory';
